name: 'Issue Key Extractor'
description: 'Github Action to extract jira keys from commit messages and output in comma delimited format. Forked from HighwayThree/jira-extract-issue-keys'
inputs:
  is-pull-request:
    description: 'if true, other input parameters will be ignored and keys from commits associated with pull request will be retrieved and parsed for Jira keys'
    required: false
    default: true

outputs:
  jira-keys:
    description: 'Jira keys that were found in input string(commit-message) in commad delimited format'
runs:
  using: 'node12'
  main: 'index.js'
